### ISSUE TITLE
MySQL protocol? is it hard to say mysql protol?

### ISSUE THREAD

**Issue by cnmade** [libsql/sqld#76] opened 2023-01-21 15:57 UTC
MySQL protocol? is it hard to say mysql protol?

**Comment by cnmade** [comment] 2023-01-21 15:58
reference: https://github.com/Expensify/Bedrock/blob/main/plugins/MySQL.cpp

**Comment by penberg** [comment] 2023-01-21 16:51
The MySQL wire protocol doesn't look that different from PostgreSQL protocol, but the issue is that MySQL language dialect is very different from SQLite whereas PostgreSQL and SQLite are actually fairly close. In fact, there's an issue open at `libsql.git` repository on improving PotgreSQL compatibility: https://github.com/libsql/libsql/issues/80 But that doesn't seem realistic with MySQL.

Btw, I am closing this issue but happy to continue discussion over at the Github discussions forum of this repository.

**Closed by penberg** 2023-01-21 16:51 UTC
